"""`POST /ask` contract (knowledge server ↔ desk/response agent). Source of truth for
``docs/api/ask.openapi.yaml`` (generated by ``scripts/export_openapi.py ask``).

Shape agreed with the desk side (their issue #14) plus the additions: ``request_id`` idempotency
key, ``feedback[]`` rejection history, ``202 queued`` admission path. The response never carries
censored spans or original text — only the reasons.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

ASK_CONTRACT_VERSION = "1.0.0"

Channel = Literal["github", "slack", "cli", "web"]
Audience = Literal["public", "company", "self"]
RefusalCode = Literal["no_task", "blocked_by_policy", "no_knowledge", "queue_full"]
CensorVerdict = Literal["allow", "redact"]

REQUEST_ID = r"^[A-Za-z0-9_.:-]{1,64}$"


class ContextItem(BaseModel):
    """One message of the external thread (untrusted input: shown to the head as data only)."""

    model_config = ConfigDict(extra="ignore")

    author: str = Field(default="", max_length=200)
    text: str = Field(max_length=8000)
    at: str = Field(default="", max_length=64)


class FeedbackItem(BaseModel):
    """One rejected draft. ``reason`` is human input (trusted, fed back into the censor rules);
    ``draft`` is external text (data only)."""

    model_config = ConfigDict(extra="ignore")

    draft: str = Field(default="", max_length=20000)
    reason: str = Field(min_length=1, max_length=1000)
    at: str = Field(default="", max_length=64)


class AskRequest(BaseModel):
    model_config = ConfigDict(extra="ignore")

    request_id: str = Field(pattern=REQUEST_ID, description="멱등키. 같은 id 재요청 시 캐시 응답")
    question: str = Field(min_length=1, max_length=10000)
    channel: Channel = Field(description="github|slack (desk). cli|web 은 개인 채팅")
    audience: Audience = Field(description="public→censor profile public, company/self→internal")
    target: str = Field(default="", max_length=500, description="스레드·이슈 식별자(계보 추적)")
    url: str | None = Field(default=None, max_length=2000)
    requester: str | None = Field(default=None, max_length=200)
    context: list[ContextItem] = Field(default_factory=list, max_length=50)
    feedback: list[FeedbackItem] = Field(default_factory=list, max_length=20)


class TaskRef(BaseModel):
    id: str
    name: str


class Refusal(BaseModel):
    code: RefusalCode
    message: str


class Redaction(BaseModel):
    reason: str = Field(description="rule id or 'llm'; spans/원문은 포함하지 않는다")


class CensorSummary(BaseModel):
    profile: str
    verdict: CensorVerdict
    redactions: list[Redaction] = Field(default_factory=list)


class AskResponse(BaseModel):
    request_id: str
    knowledge: str = Field(description="검열을 통과한 텍스트. refusal 이 있으면 빈 문자열")
    task: TaskRef | None
    refusal: Refusal | None
    censor: CensorSummary


class QueuedResponse(BaseModel):
    request_id: str
    status: Literal["queued"] = "queued"
    position: int = Field(ge=1)


class ErrorBody(BaseModel):
    code: str
    detail: str | None = None


class TeamCreateRequest(BaseModel):
    """`POST /teams`: requirements in natural language → resident task team (supervisor + members)."""

    model_config = ConfigDict(extra="ignore")

    task_id: str | None = Field(default=None, pattern=r"^[a-z][a-z0-9_-]{0,31}$", description="생략 시 name 에서 slug")
    name: str = Field(min_length=1, max_length=200)
    description: str = Field(min_length=1, max_length=4000)
    sandbox: str | None = Field(default=None, description="선언된 샌드박스로 격리할 때만. 기본은 기본 샌드박스")


class TeamMemberView(BaseModel):
    agent_id: str
    role: str
    groups: list[str] = []
    alias: str | None = None


class TeamPatternView(BaseModel):
    capabilities: list[str] = []
    roles: list[str] = []
    source: Literal["direct", "keywords", "fallback", "manual"] = "manual"
    reason: str = ""


class TeamApplied(BaseModel):
    manifest: str | None = None
    agents_apply: Literal["ok", "error", "skipped"] = "skipped"
    seeded: int = 0
    error: str | None = None


class TeamResponse(BaseModel):
    team_id: str
    task: TaskRef
    pattern: TeamPatternView
    supervisor: str
    members: list[TeamMemberView]
    sandbox: str | None
    status: Literal["ready", "applying", "failed", "declared"]
    applied: TeamApplied | None = None
    error: str | None = None
    created_at: str = ""


class TeamList(BaseModel):
    teams: list[TeamResponse]


class ChatRequest(BaseModel):
    """Personal chat (audience self) — same ``ask()`` function, request_id issued by the server."""

    model_config = ConfigDict(extra="ignore")

    question: str = Field(min_length=1, max_length=10000)
    session_id: str | None = Field(default=None, pattern=REQUEST_ID)
    channel: Literal["cli", "web"] = "web"


__all__ = [
    "ASK_CONTRACT_VERSION", "AskRequest", "AskResponse", "QueuedResponse", "ErrorBody", "ChatRequest",
    "ContextItem", "FeedbackItem", "TaskRef", "Refusal", "Redaction", "CensorSummary",
    "TeamCreateRequest", "TeamResponse", "TeamList", "TeamApplied", "TeamPatternView", "TeamMemberView",
]
