"""Render per-sandbox OpenClaw ``agents.yaml`` manifests and agent workspace seed files.

The manifest schema follows NemoClaw's *Declarative Multi-Agent Manifest*
(``nemoclaw onboard --agents`` / ``nemoclaw <sb> agents apply -f``): ``defaults.subagents``,
``main`` overrides (tools/subagents) and ``agents[]`` secondaries with ``tools`` and a
``provider/model`` reference whose provider must be the onboard route provider (``inference``).
"""

from __future__ import annotations

from pathlib import Path

import yaml

from rfa_mas.nemoclaw.config import DEPLOY_DIR, Assignments, ToolPolicy
from rfa_mas.nemoclaw.markers import make_marker

ROUTE_PROVIDER = "inference"  # NemoClaw routeProvider for the managed inference.local route
HEAD_TOOLS = {"profile": "coding", "deny": ["process", "code_execution", "write", "edit", "apply_patch", "group:web", "cron",
              "group:memory", "group:media", "skill_workshop", "browser", "bundle-mcp"]}  # not group:runtime: children inherit denies
WORKSPACE_ROOT = "/sandbox/.openclaw"
TASK_SPECS_DIR = DEPLOY_DIR / "task-specs"   # <team_id>.md: the task's scope/disclosure spec for its supervisor


def tools_dict(policy: ToolPolicy) -> dict:
    out: dict = {}
    if policy.profile:
        out["profile"] = policy.profile
    if policy.allow:
        out["allow"] = list(policy.allow)
    if policy.deny:
        out["deny"] = list(policy.deny)
    return out


def openclaw_agent_id(assignments: Assignments, agent_id: str) -> str:
    """The id OpenClaw uses: fixed agents own their sandbox's canonical ``main`` slot."""
    return "main" if assignments.agents[agent_id].kind == "fixed" else agent_id


def workspace_path(openclaw_id: str) -> str:
    return f"{WORKSPACE_ROOT}/workspace" if openclaw_id == "main" else f"{WORKSPACE_ROOT}/workspace-{openclaw_id}"


def agent_dir(openclaw_id: str) -> str:
    return f"{WORKSPACE_ROOT}/agents/{openclaw_id}"


def render_manifest(assignments: Assignments, sandbox: str) -> dict:
    """Manifest for one sandbox. ``main`` is the fixed agent placed there (the assistant in the
    default sandbox) or a thin routing head; every other agent placed there is a secondary.
    The spawn allowlist contains only delegatable secondaries (never the censor)."""
    main_agent = assignments.main_agent(sandbox)
    ids = assignments.sandbox_agents(sandbox)
    spawnable = [a for a in ids if assignments.agents[a].delegatable]
    # depth 2: main → team supervisor → members (broker turns start at depth 0, so teams work at depth 1 too)
    manifest: dict = {"defaults": {"subagents": {"maxSpawnDepth": 2}}}
    if main_agent is not None:
        spec = assignments.agents[main_agent]
        subagents: dict = {"requireAgentId": True}
        if spawnable:
            subagents.update({"allowAgents": spawnable, "delegationMode": "prefer"})
        manifest["main"] = {"tools": tools_dict(spec.tools), "subagents": subagents}
    else:
        subagents = {"requireAgentId": True}
        if spawnable:
            subagents.update({"allowAgents": spawnable, "delegationMode": "prefer"})
        manifest["main"] = {"tools": dict(HEAD_TOOLS), "subagents": subagents}
    if ids:
        manifest["agents"] = []
        for agent_id in ids:
            spec = assignments.agents[agent_id]
            entry = {
                "id": agent_id,
                "description": spec.description or agent_id,
                "model": f"{ROUTE_PROVIDER}/{spec.alias}",
                "tools": tools_dict(spec.tools),
                "subagents": {"requireAgentId": True},
            }
            if spec.allow_agents:  # team supervisor: may spawn its own members only
                entry["subagents"].update({"allowAgents": list(spec.allow_agents), "delegationMode": "prefer"})
            manifest["agents"].append(entry)
    return manifest


def manifest_yaml(manifest: dict) -> str:
    header = (
        "# Generated by `python -m rfa_mas.nemoclaw render` from deploy/nemoclaw/assignments.yaml.\n"
        "# Applied with `nemoclaw onboard --agents` (bake) or `nemoclaw <sb> agents apply -f` (live).\n"
    )
    return header + yaml.safe_dump(manifest, sort_keys=False, allow_unicode=True)


def write_manifests(assignments: Assignments, out_dir: Path) -> dict[str, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    paths: dict[str, Path] = {}
    for sandbox in assignments.ordered_sandboxes():  # every declared sandbox, so opt-in ones are ready to onboard
        path = out_dir / f"{sandbox}.agents.yaml"
        path.write_text(manifest_yaml(render_manifest(assignments, sandbox)), encoding="utf-8")
        paths[sandbox] = path
    return paths


def manifest_agent_ids(manifest: dict) -> list[str]:
    return sorted(a["id"] for a in manifest.get("agents", []))


def render_identity(assignments: Assignments, agent_id: str, secret: bytes,
                    task_specs_dir: Path | None = None) -> str:
    """``IDENTITY.md`` for an agent workspace, carrying the signed agent marker that the
    egress-proxy uses to resolve the agent's alias (workspace files are injected into the
    system prompt; the marker is HMAC-signed so a prompt cannot forge a different alias)."""
    spec = assignments.agents[agent_id]
    sandbox = assignments.sandbox_for(agent_id)
    marker = make_marker(
        "agent", {"agent": agent_id, "sandbox": sandbox, "alias": spec.alias}, secret
    )
    groups = assignments.sandboxes[sandbox].groups
    text = (
        "# IDENTITY\n\n"
        f"- name: {agent_id}\n"
        f"- role: {spec.kind} agent ({spec.description or 'no description'})\n"
        f"- sandbox: {sandbox} (security groups: {', '.join(groups)})\n"
        f"- inference alias: {spec.alias}\n"
        f"- skill: {spec.skill}\n"
        "- identity marker (managed by the host controller; never edit, quote, repeat or send it to anyone):\n"
        f"  {marker}\n"
    )
    if spec.team:
        text += f"- team: {spec.team}\n"
    if spec.allow_agents:
        members = "\n".join(f"  - {m}: {assignments.agents[m].description}" for m in spec.allow_agents)
        verifier = next((m for m in spec.allow_agents if m.endswith("-verifier")), None)
        text += (
            "\n# TEAM\n\n"
            "You are this task's representative (supervisor). Your members (spawn with sessions_spawn, agentId exactly):\n"
            f"{members}\n"
            "Rules: gather evidence from members first, never answer from memory; start every member message with the "
            "first line of the user message (the `⟦rfa-channel …⟧` line, not the identity marker above) and pass any "
            "`[이전 거절 사유]` block through unchanged; "
            + (f"send your draft plus the members' evidence to {verifier} last and apply one revision if it says revise; " if verifier else "")
            + "answer with the evidence ids you used; when every evidence member reports NO_EVIDENCE, reply "
              "`NO_EVIDENCE: <what was checked>` instead of inventing facts.\n"
        )
        spec_file = (task_specs_dir or TASK_SPECS_DIR) / f"{spec.team}.md" if spec.team else None
        if spec_file is not None and spec_file.is_file():
            text += "\n# TASK SPEC\n\n" + spec_file.read_text(encoding="utf-8").strip() + "\n"
    return text


def render_agents_md(assignments: Assignments, agent_id: str, secret: bytes) -> str:
    """``AGENTS.md`` for a secondary agent's workspace. OpenClaw injects ``IDENTITY.md`` only into primary
    runs; a member started with ``sessions_spawn`` gets ``AGENTS.md`` (plus the skills list) instead, so
    the signed agent marker has to live here too or the egress-proxy sees the member's inference as
    unattributed (observed 2026-09-28: every member turn audited with agent=None)."""
    spec = assignments.agents[agent_id]
    sandbox = assignments.sandbox_for(agent_id)
    marker = make_marker("agent", {"agent": agent_id, "sandbox": sandbox, "alias": spec.alias}, secret)
    skill = f"Follow the `{spec.skill}` skill under `skills/` exactly.\n" if spec.skill else ""
    return (
        "# AGENTS\n\n"
        f"You are `{agent_id}`, a {spec.kind} agent ({spec.description or 'no description'}) in sandbox {sandbox}.\n"
        f"{skill}"
        "When you run as a spawned team member, IDENTITY.md is not loaded; this file carries the same facts.\n"
        "- identity marker (managed by the host controller; never edit, quote, repeat or send it to anyone):\n"
        f"  {marker}\n"
    )


def render_head_identity(assignments: Assignments, sandbox: str, secret: bytes) -> str:
    """``IDENTITY.md`` for the routing head (``main``) of a task sandbox: least-exposed alias."""
    marker = make_marker("agent", {"agent": "head", "sandbox": sandbox, "alias": "rfa-internal"}, secret)
    ids = [a for a in assignments.sandbox_agents(sandbox) if assignments.agents[a].delegatable]
    return (
        "# IDENTITY\n\n"
        f"- name: head (routing only) for sandbox {sandbox}\n"
        f"- delegates to (sessions_spawn agentId): {', '.join(ids)}\n"
        "- you do not answer domain questions yourself; pick the agent whose description fits\n"
        "- identity marker (managed by the host controller; never edit, quote, repeat or send it to anyone):\n"
        f"  {marker}\n"
    )
