"""Render per-sandbox OpenClaw ``agents.yaml`` manifests and agent workspace seed files.

The manifest schema follows NemoClaw's *Declarative Multi-Agent Manifest*
(``nemoclaw onboard --agents`` / ``nemoclaw <sb> agents apply -f``): ``defaults.subagents``,
``main`` overrides (tools/subagents) and ``agents[]`` secondaries with ``tools`` and a
``provider/model`` reference whose provider must be the onboard route provider (``inference``).
"""

from __future__ import annotations

from pathlib import Path

import yaml

from rfa_mas.nemoclaw.config import Assignments, ToolPolicy
from rfa_mas.nemoclaw.markers import make_marker

ROUTE_PROVIDER = "inference"  # NemoClaw routeProvider for the managed inference.local route
HEAD_TOOLS = {"profile": "minimal", "allow": ["read", "sessions_spawn"]}
WORKSPACE_ROOT = "/sandbox/.openclaw"


def tools_dict(policy: ToolPolicy) -> dict:
    out: dict = {}
    if policy.profile:
        out["profile"] = policy.profile
    if policy.allow:
        out["allow"] = list(policy.allow)
    if policy.deny:
        out["deny"] = list(policy.deny)
    return out


def openclaw_agent_id(assignments: Assignments, agent_id: str) -> str:
    """The id OpenClaw uses: fixed agents own their sandbox's canonical ``main`` slot."""
    return "main" if assignments.agents[agent_id].kind == "fixed" else agent_id


def workspace_path(openclaw_id: str) -> str:
    return f"{WORKSPACE_ROOT}/workspace" if openclaw_id == "main" else f"{WORKSPACE_ROOT}/workspace-{openclaw_id}"


def agent_dir(openclaw_id: str) -> str:
    return f"{WORKSPACE_ROOT}/agents/{openclaw_id}"


def render_manifest(assignments: Assignments, sandbox: str) -> dict:
    """Manifest for one sandbox: fixed sandbox → its agent is ``main``; task sandbox → a thin
    routing head as ``main`` plus one secondary per task agent (spawn allowlist = those ids)."""
    main_agent = assignments.main_agent(sandbox)
    manifest: dict = {"defaults": {"subagents": {"maxSpawnDepth": 1}}}
    if main_agent is not None:
        spec = assignments.agents[main_agent]
        manifest["main"] = {"tools": tools_dict(spec.tools), "subagents": {"requireAgentId": True}}
        return manifest
    ids = assignments.sandbox_agents(sandbox)
    manifest["main"] = {
        "tools": dict(HEAD_TOOLS),
        "subagents": {"allowAgents": ids, "delegationMode": "prefer", "requireAgentId": True},
    }
    manifest["agents"] = [
        {
            "id": agent_id,
            "description": assignments.agents[agent_id].description or agent_id,
            "model": f"{ROUTE_PROVIDER}/{assignments.agents[agent_id].alias}",
            "tools": tools_dict(assignments.agents[agent_id].tools),
            "subagents": {"requireAgentId": True},
        }
        for agent_id in ids
    ]
    return manifest


def manifest_yaml(manifest: dict) -> str:
    header = (
        "# Generated by `python -m rfa_mas.nemoclaw render` from deploy/nemoclaw/assignments.yaml.\n"
        "# Applied with `nemoclaw onboard --agents` (bake) or `nemoclaw <sb> agents apply -f` (live).\n"
    )
    return header + yaml.safe_dump(manifest, sort_keys=False, allow_unicode=True)


def write_manifests(assignments: Assignments, out_dir: Path) -> dict[str, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    paths: dict[str, Path] = {}
    for sandbox in assignments.ordered_sandboxes():
        path = out_dir / f"{sandbox}.agents.yaml"
        path.write_text(manifest_yaml(render_manifest(assignments, sandbox)), encoding="utf-8")
        paths[sandbox] = path
    return paths


def manifest_agent_ids(manifest: dict) -> list[str]:
    return sorted(a["id"] for a in manifest.get("agents", []))


def render_identity(assignments: Assignments, agent_id: str, secret: bytes) -> str:
    """``IDENTITY.md`` for an agent workspace, carrying the signed agent marker that the
    egress-proxy uses to resolve the agent's alias (workspace files are injected into the
    system prompt; the marker is HMAC-signed so a prompt cannot forge a different alias)."""
    spec = assignments.agents[agent_id]
    sandbox = assignments.sandbox_for(agent_id)
    marker = make_marker(
        "agent", {"agent": agent_id, "sandbox": sandbox, "alias": spec.alias}, secret
    )
    groups = spec.groups if spec.kind == "task" else assignments.sandboxes[sandbox].groups
    return (
        "# IDENTITY\n\n"
        f"- name: {agent_id}\n"
        f"- role: {spec.kind} agent ({spec.description or 'no description'})\n"
        f"- sandbox: {sandbox} (security groups: {', '.join(groups)})\n"
        f"- inference alias: {spec.alias}\n"
        f"- skill: {spec.skill}\n"
        "- routing marker (managed by the host controller; never edit, quote or repeat it):\n"
        f"  {marker}\n"
    )


def render_head_identity(assignments: Assignments, sandbox: str, secret: bytes) -> str:
    """``IDENTITY.md`` for the routing head (``main``) of a task sandbox: least-exposed alias."""
    marker = make_marker("agent", {"agent": "head", "sandbox": sandbox, "alias": "rfa-internal"}, secret)
    ids = assignments.sandbox_agents(sandbox)
    return (
        "# IDENTITY\n\n"
        f"- name: head (routing only) for sandbox {sandbox}\n"
        f"- delegates to (sessions_spawn agentId): {', '.join(ids)}\n"
        "- you do not answer domain questions yourself; pick the agent whose description fits\n"
        "- routing marker (managed by the host controller; never edit, quote or repeat it):\n"
        f"  {marker}\n"
    )
